import './globals.css';
import ContextProvider from '@/context/contextProvider';
import { Roboto } from 'next/font/google';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const roboto = Roboto({
  weight: ['400', '500', '900'],
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} tracking-wide`}>
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}
